"""message

Revision ID: f31328eb36dd
Revises: 
Create Date: 2025-11-10 12:15:16.940017

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = 'f31328eb36dd'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('complaint', schema=None) as batch_op:
        batch_op.create_foreign_key(None, 'staff', ['assigned_staff_id'], ['staff_id'])

    with op.batch_alter_table('housing_units', schema=None) as batch_op:
        batch_op.create_foreign_key(None, 'blocks', ['block_id'], ['id'])

    with op.batch_alter_table('login', schema=None) as batch_op:
        batch_op.alter_column('member_id',
               existing_type=mysql.VARCHAR(length=50),
               nullable=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('login', schema=None) as batch_op:
        batch_op.alter_column('member_id',
               existing_type=mysql.VARCHAR(length=50),
               nullable=False)

    with op.batch_alter_table('housing_units', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')

    with op.batch_alter_table('complaint', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')

    # ### end Alembic commands ###
